Algoritmo "AtividadeNumeroSucessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : O usúario digita um número e o algoritmo mostra para ele o seu antecessor! (função)
// Autor(a)    : Renan Paulino
// Data atual  : 14/03/2025
Var
// Seção de Declarações das variáveis 
 Numero01: inteiro
 Sucessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Digite um número para lhe monstrar o seu sucessor: ")
  leia (numero01)
  Sucessor <- numero01 + 1
  escreva("O sucessor é o número: ", Sucessor)

Fimalgoritmo