Algoritmo "Contadora1a10"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   :  Jailson Costa dos Santos
// Descrição   : Programa que exibe do 1 ao 10
// Autor(a)    : Renan Paulino
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis 
   contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   contadora <- 1
   enquanto contadora <= 10 faca
            escreval(contadora)
            contadora <- contadora + 1
   fimenquanto
            

Fimalgoritmo