Algoritmo "DesvioCondicionalComposto"
// Disciplina   : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita um determinado valor e identifica se o número é maior ou menor que 10
// Autor(a)    : Renan Paulino
// Data atual  : 14/03/2025
Var
// Seção de Declarações das variáveis
numero01: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Desvio Condicional Simples")
escreva ("Digite um número inteiro: ")
leia(numero01)
  se numero01 < 10 entao
     escreval("numero é menor que 10")
  senao
     escreval("número maior que 10")
  fimse

Fimalgoritmo