Algoritmo "DesvioCondicionalSimples"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/03/2025
Var
// Seção de Declarações das variáveis 
numero01: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Desvio Condicional Simples")
escreva ("Digite um número inteiro: ")
leia(numero01)
  se numero01 < 10 entao
    escreval("numero é menor que 10")
  fimse

Fimalgoritmo