Algoritmo "EstruturaRepetição"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Renan Paulino
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis 
contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   enquanto contadora < 10 faca
       escreval("Somente a Dor Coletiva Gera União ",contadora)
       contadora <- contadora + 1
   fimenquanto


Fimalgoritmo