Algoritmo "Exercicio14"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Diz se u número digitado é menor, maior ou igual a 10! (função)
// Autor(a)    : Renan Paulino
// Data atual  : 19/03/2025
Var
   // Seção de Declarações das variáveis
   Numero01: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite um valor para eu te dizer se é maior ou menor do que 10: ")
   leia (numero01)
   se numero01 > 10 entao
      escreva("O número é maior do que 10")
   senao
      se numero01 < 10 entao
         escreva("O número é menor do que 10")
      senao
         escreva("O número é igual a 10")

      fimse
   fimse

Fimalgoritmo