Algoritmo "Multiplicacao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/03/2025
Var
// Seção de Declarações das variáveis 
 numero1, numero2, multi: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Bem vindo a área de Multiplicação!")
 escreva("Digite um número para ser multiplicado:")
 leia(numero1)
 escreva("Digite outro número para multiplicar o primeiro valor:")
 leia(numero2)
 multi <- numero1 * numero2
 escreva("O resultado da divisão é:", multi)


Fimalgoritmo