Algoritmo "Soma"
// Disciplina   : [Lógica de Programação JavaScript]
// Professor   : Jailson Costa da Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/03/2025
Var
// Seção de Declarações das variáveis 
  numero1, numero2, soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Bem vindo a área de soma!")
 escreva("Digite um número para soma:")
 leia(numero1)
 escreva("Digite outro número para a soma:")
 leia(numero2)
 soma <- numero1 + numero2
 escreva("O resultado da soma é:", soma)
 

Fimalgoritmo