Algoritmo "Subtracao"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Subtrai dois valores! (função)
// Autor(a)    : Renan Paulino
// Data atual  : 14/03/2025
Var
// Seção de Declarações das variáveis 
  numero1, numero2, sub: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Bem vindo a área de subtração!")
 escreva("Digite um número para subtração:")
 leia(numero1)
 escreva("Digite outro número para a subtração:")
 leia(numero2)
 sub <- numero1 - numero2
 escreva("O resultado da subtração é:", sub)

Fimalgoritmo