Algoritmo "semnome"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Renan Paulino
// Data atual  : 28/03/2025
Var
// Seção de Declarações das variáveis 
   contadora, contadora1, contadora2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para contadora de 5 ate 0 passo - 1 faca
        para contadora1 de 59 ate 0 passo -1 faca
             para contadora2 de 59 ate 0 passo -1 faca
              escreval(contadora, " : ", contadora1, " : ", contadora2)
             fimpara
        fimpara
   fimpara

Fimalgoritmo