Algoritmo "ExerciciosManzano-PAG66-L05E"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Apresenta os números impares de 0 a 20.
// Autor(a)    : Renan Paulino
// Data atual  : 13/04/2025
Var
// Seção de Declarações das variáveis 
    numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Números ímpares de 0 a 20:")

   para numero de 0 ate 20 faca
      se numero % 2 <> 0 entao
         escreva(numero, " ")
      fimse
   fimpara

Fimalgoritmo