Algoritmo "ExerciciosManzano-PAG50-L05A"
// Disciplina   : [Lógica de Programação do VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exercicios feito com a estrutura de repetição para
// Autor(a)    : Renan Paulino
// Data atual  : 13/04/2025
Var
// Seção de Declarações das variáveis 
    numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Quadrados dos números inteiros de 15 a 200:")

   para numero de 15 ate 200 faca
      escreval(numero, "² = ", numero * numero)
   fimpara

Fimalgoritmo