Algoritmo "ExerciciosManzano-PAG66-L05F"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Apresenta os números impares de 0 a 20.
// Autor(a)    : Renan Paulino
// Data atual  : 13/04/2025
Var
// Seção de Declarações das variáveis 
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Valores Divisíveis por Quatro")

   para numero de 1 ate 200 faca
      se numero % 4 = 0 entao
         escreva(numero, " ")
      fimse
   fimpara
   
Fimalgoritmo