Algoritmo "ExerciciosManzano-pag25-7G"
// Disciplina   : [Lógica de Programação Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Lê quatro números inteiros e apresentar o resultado da adição e multiplicação, baseando-se na utilização do conceito da propriedade distribuitiva.
// Autor(a)    : Renan Paulino
// Data atual  : 29/03/2025
Var
// Seção de Declarações das variáveis 
    A, B, C, D: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor de A: ")
   leia(A)
   escreva("Digite o valor de B: ")
   leia(B)
   escreva("Digite o valor de C: ")
   leia(C)
   escreva("Digite o valor de D: ")
   leia(D)
   
   escreval("Operações envolvendo A:")
   escreval("A + B = ", A + B)
   escreval("A × B = ", A * B)
   escreval("A + C = ", A + C)
   escreval("A × C = ", A * C)
   escreval("A + D = ", A + D)
   escreval("A × D = ", A * D)

   escreval("Operações envolvendo B:")
   escreval("B + C = ", B + C)
   escreval("B × C = ", B * C)
   escreval("B + D = ", B + D)
   escreval("B × D = ", B * D)

   escreval("Operações envolvendo C:")
   escreval("C + D = ", C + D)
   escreval("C × D = ", C * D)

Fimalgoritmo