Algoritmo "ExerciciosManzano-PAG66-L05C"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros.
// Autor(a)    : Renan Paulino
// Data atual  : 13/04/2025
Var
// Seção de Declarações das variáveis 
 valor, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para valor de 1 até 100 faca
     soma <- valor + soma
fimpara

escreval("A soma dos cem primeiros números inteiros é: ", soma)


Fimalgoritmo